'use client';
import {useEffect,useState} from 'react'; import {supabase} from '@/lib/supabase';
export default function Dashboard(){const [msg,setMsg]=useState('Pronto para registrar.'),[rows,setRows]=useState<any[]>([]),[name,setName]=useState(''),[busy,setBusy]=useState(false);
async function load(){const s=supabase();const {data:{user}}=await s.auth.getUser();if(!user)return location.href='/';const [{data:p},{data:r}]=await Promise.all([s.from('profiles').select('name').eq('id',user.id).single(),s.from('time_entries').select('*').eq('employee_id',user.id).order('created_at',{ascending:false}).limit(60)]);setName(p?.name||'');setRows(r||[])}useEffect(()=>{load()},[]);
async function punch(){if(busy)return;setBusy(true);setMsg('Obtendo localização...');navigator.geolocation.getCurrentPosition(async pos=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Recife'}).format(new Date());const todayRows=rows.filter(r=>r.work_date===today);const needsSelfie=todayRows.length===0||todayRows.some(r=>r.kind==='retorno_intervalo')||todayRows.length===1&&todayRows[0].kind==='entrada'&&false;let file:File|null=null;const send=async()=>{setMsg('Validando no servidor...');const fd=new FormData();fd.append('latitude',String(pos.coords.latitude));fd.append('longitude',String(pos.coords.longitude));fd.append('accuracy',String(pos.coords.accuracy));if(file)fd.append('selfie',file);const s=supabase();const {data:{session}}=await s.auth.getSession();const res=await fetch('/api/punch',{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`},body:fd});const j=await res.json();setMsg(j.message||j.error||'Erro');setBusy(false);if(res.ok)load()};
// O servidor é a autoridade; tentamos selfie na primeira batida e, se necessário, na saída.
if(todayRows.length===0||todayRows.at(0)?.kind==='retorno_intervalo'||todayRows.length===1&&todayRows[0].kind==='entrada'){const input=document.createElement('input');input.type='file';input.accept='image/*';input.capture='user';input.onchange=()=>{file=input.files?.[0]||null;if(!file){setBusy(false);setMsg('Selfie cancelada.');return}send()};input.click()}else send();},e=>{setBusy(false);setMsg('Localização indisponível: '+e.message)},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function logout(){await supabase().auth.signOut();location.href='/'}
return <main><div className="top"><div><div className="brand">Ailton Hortifruti</div><h1>Meu ponto</h1><p className="muted">{name}</p></div><button className="linkbtn" onClick={logout}>Sair</button></div><div className="card hero"><p>{msg}</p><button disabled={busy} onClick={punch}>{busy?'Aguarde...':'📍 Registrar ponto'}</button><small>Raio de 80 m. Selfie exigida na entrada e saída final. GPS impreciso é sinalizado.</small></div><div className="card"><h2>Histórico</h2>{rows.length===0?<p className="muted">Nenhum registro.</p>:rows.map(r=><div className="row" key={r.id}><div><b>{String(r.kind).replaceAll('_',' ')}</b>{r.suspicious&&<span className="badge warn"> GPS suspeito</span>}</div><small>{new Date(r.created_at).toLocaleString('pt-BR',{timeZone:'America/Recife'})} • {Math.round(r.distance_m||0)} m • precisão ±{Math.round(r.accuracy_m||0)} m</small></div>)}</div></main>}
